{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "side-project-chart.fullname" . }}-gateway
  namespace: {{ .Values.istio.namespace | default .Release.Namespace }}
spec:
  selector:
    istio: {{ .Values.istio.ingressSelector | default "ingressgateway" }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
{{- end }}
