{{- if and (eq .Values.rollout.strategy "blueGreen") .Values.rollout.blueGreen.previewService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "side-project-chart.fullname" . }}-preview
  labels:
    {{- include "side-project-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "side-project-chart.selectorLabels" . | nindent 4 }}
{{- end }}

