apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "side-project-chart.fullname" . }}
  labels:
    {{- include "side-project-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.rollout.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "side-project-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "side-project-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "side-project-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    {{- if eq .Values.rollout.strategy "blueGreen" }}
    blueGreen:
      activeService: {{ include "side-project-chart.fullname" . }}
      {{- if .Values.rollout.blueGreen.previewService }}
      previewService: {{ include "side-project-chart.fullname" . }}-preview
      {{- end }}
      autoPromotionEnabled: {{ .Values.rollout.blueGreen.autoPromotionEnabled | default false }}
      {{- with .Values.rollout.blueGreen.scaleDownDelaySeconds }}
      scaleDownDelaySeconds: {{ . }}
      {{- end }}
      {{- with .Values.rollout.blueGreen.prePromotionAnalysis }}
      prePromotionAnalysis:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rollout.blueGreen.postPromotionAnalysis }}
      postPromotionAnalysis:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- else }}
    canary:
      {{- with .Values.rollout.canary.steps }}
      steps:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rollout.canary.maxSurge }}
      maxSurge: {{ . }}
      {{- end }}
      {{- with .Values.rollout.canary.maxUnavailable }}
      maxUnavailable: {{ . }}
      {{- end }}
      {{- with .Values.rollout.canary.analysis }}
      analysis:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rollout.canary.trafficRouting }}
      trafficRouting:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}

