apiVersion: v1
kind: Service
metadata:
  name: side-project-service-1
  labels:
    {{- include "side-project-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "side-project-chart.selectorLabels" . | nindent 4 }}
