{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "side-project-chart.fullname" . }}-vs
  namespace: {{ .Values.istio.namespace | default .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "side-project-chart.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "side-project-chart.fullname" . }}
        port:
          number: {{ .Values.service.port }}
    retries:
      attempts: {{ .Values.istio.retries.attempts | default 3 }}
      perTryTimeout: {{ .Values.istio.retries.perTryTimeout | default "2s" }}
{{- end }}
