name: Side Project Workflow

on:
  workflow_dispatch:
    inputs:
      aws_account_id:
        description: AWS Account ID
        type: string  
      tag_name:
        type: string 
        description: tag name
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}
      full_image: ${{ steps.build-publish.outputs.full_image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::256344107989:role/GitHubActionsRole
          aws-region: il-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries:  ${{ inputs.aws_account_id }}
          mask-password: "true" # see: https://github.com/aws-actions/amazon-ecr-login#docker-credentials

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: side-project-test
          IMAGE_TAG: latest
        run: |
          docker build . -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Package and push Helm Chart to Amazon ECR
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: side-project-chart
        run : |
          helm package side-project-chart --app-version ${{ inputs.tag_name }} --version ${{ inputs.tag_name }}
          helm push "side-project-chart-${{ inputs.tag_name }}.tgz" oci://$ECR_REGISTRY


      - name: Deploy Helm Chart to EKS Cluster
        id: deploy-helm
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        uses: aws-actions/eks-kubectl-action@v1
        with:
          cluster-name: side-project-cluster
          role-to-assume: arn:aws:iam::256344107989:role/GitHubActionsRole
          aws-region: il-central-1
          helm: |
            upgrade --install side-project-release $ECR_REGISTRY/side-project-chart:latest
