name: Side Project Workflow

on:
  workflow_dispatch:
    inputs:
      aws_account_id:
        description: AWS Account ID
        type: string  
      tag_name:
        type: string 
        description: tag name
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}
      full_image: ${{ steps.build-publish.outputs.full_image }}
      application_applied: ${{ steps.apply-application.outputs.application_applied }}   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::256344107989:role/GitHubActionsRole
          aws-region: il-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries:  ${{ inputs.aws_account_id }}
          mask-password: "true" # see: https://github.com/aws-actions/amazon-ecr-login#docker-credentials

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push multi-arch image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: side-project-test
          IMAGE_TAG: latest
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" \
            .
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

#      - name: Configure kubectl for EKS
#        shell: bash
#        run: |
#          aws eks update-kubeconfig --name side-project-eks --region il-central-1
#          kubectl get nodes
#
#      - name: apply application to ArgoCD
#        id: apply-application
#        shell: bash
#        run: |
#          kubectl apply -f argocd/application.yaml
#          echo "Application is applied to ArgoCD"
